services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    Company\DocumentBundle\Form\Type\:
        resource: '../../Form/Type/*'
        tags:
            - { name: 'form.type' }
