# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: false
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Company\DocumentBundle\Doctrine\EventSubscriber\:
        resource: '../../Doctrine/EventSubscriber/*'
        tags:
            - { name: 'doctrine.event_subscriber' }

    Company\DocumentBundle\Service\:
        resource: '../../Service/*'

    Company\DocumentBundle\Service\DocumentTransformer\:
        resource: '../../Service/DocumentTransformer/*'
        tags:
            - { name: 'company.document.transformer' }

