services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    Company\FormCookieBundle\Service\:
        resource: '../../Service/*'

    Company\FormCookieBundle\Service\CachedFormDataService:
        arguments:
            $cachePool: '@company.cache.cookie'

    Company\FormCookieBundle\Form\Extension\:
        resource: '../../Form/Extension/*'
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
