services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    Company\FormChangeConfirmationBundle\Form\Extension\:
        resource: '../../Form/Extension/*'
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
